In [1]:
import torch

# number of entries in our database 
num_entries = 5000

db = torch.rand(num_entries) > 0.5
db = db.type(torch.ByteTensor)
db

tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8)

In [2]:
remove_index = 2

In [3]:
def get_parallel_db(db, remove_index):
    
    return torch.cat((db[0:remove_index],
                     db[remove_index+1:]))

In [4]:
get_parallel_db(db,2)

tensor([1, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [5]:
get_parallel_db(db, 532322).shape

torch.Size([5000])

In [6]:
parallel_dbs = list()

In [7]:
def get_parallel_dbs(db):
    
    parallel_dbs = list()

    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
        
    return parallel_dbs

In [8]:
pdbs = get_parallel_dbs(db)
pdbs

[tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 1

In [9]:
def create_db_and_parallels(num_entries):
    
    db = torch.rand(num_entries) > 0.5
    db = db.type(torch.ByteTensor)
    pdbs = get_parallel_dbs(db)
        
    return db, pdbs

In [10]:
db, pdbs = create_db_and_parallels(20)

In [11]:
pdbs


[tensor([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,

In [12]:
db, pdbs = create_db_and_parallels(20)

In [13]:
#db = db.type(torch.ByteTensor)
db


tensor([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1],
       dtype=torch.uint8)

In [14]:
def query(db):
    return db.sum()

In [15]:
query(db)

tensor(12)

In [16]:
query(pdbs[19])

tensor(11)

In [17]:
# Evaluating Privacy ( Lesson 3 )

In [18]:
db, pdbs = create_db_and_parallels(20)

In [19]:
db

tensor([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       dtype=torch.uint8)

In [20]:
full_db_result = query(db)

In [21]:
max_distance = 0

for pdb in pdbs:
    pdb_result = query(pdb)
    
    db_distance = torch.abs(pdb_result - full_db_result)
    
    if(db_distance > max_distance):
        max_distance = db_distance

In [22]:
def sensitivity(query, n_entries=1000):
    
    db, pdbs = create_db_and_parallels(n_entries)
    
    full_db_result = query(db)
    
    max_distance = 0

    for pdb in pdbs:
        pdb_result = query(pdb)

        db_distance = torch.abs(pdb_result - full_db_result)

        if(db_distance > max_distance):
            max_distance = db_distance
            
    return max_distance

In [23]:
def query(db):
    return db.float().mean()

In [24]:
sensitivity(query)

tensor(0.0005)

In [25]:
# Calculate Sensitivity L1 for Threshold

In [26]:
def query(db, threshold = 5):
    return (db.sum() > threshold).float()

In [27]:
db, pdbs = create_db_and_parallels(10)
db.sum()

tensor(3)

In [28]:
db.sum() > 5

tensor(False)

In [29]:
query(db)

tensor(0.)

In [30]:
for i in range(10):

    sens_f = sensitivity(query, n_entries = 10)
    print(sens_f)

0
0
0
0
tensor(1.)
tensor(1.)
0
0
0
tensor(1.)


In [31]:
# Differencing Attack

In [32]:
db, _ = create_db_and_parallels(100)

In [33]:
db

tensor([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0], dtype=torch.uint8)

In [34]:
pdb = get_parallel_db(db, remove_index=10)

In [35]:
db[10]

tensor(0, dtype=torch.uint8)

In [36]:
# differencing attack using a sum query

sum(db) - sum(pdb)

tensor(0, dtype=torch.uint8)

In [37]:
# differencing attack using a mean query

(sum(db).float() / len(db)) - (sum(pdb).float() / len(db))

tensor(0.)

In [38]:
# differencing attack using threshold

(sum(db).float() > 49 ).type(torch.ByteTensor) - (sum(pdb).float() > 49).type(torch.ByteTensor)

tensor(0, dtype=torch.uint8)

In [39]:
# Implementing Local Differential Privacy

In [40]:
db, pdbs = create_db_and_parallels(100)


In [41]:
true_result = torch.mean(db.float())
true_result

tensor(0.5100)

In [42]:
first_coin_flip = (torch.rand(len(db))>0.5).float()
second_coin_flip = (torch.rand(len(db))>0.5).float()

In [43]:
db = first_coin_flip

In [44]:
second_coin_flip

tensor([0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0.,
        1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
        0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 1., 0., 0., 0., 0., 0.])

In [45]:
db.float()

tensor([1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
        1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
        0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1.,
        0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
        0., 1., 0., 0., 1., 1., 1., 1., 1., 1.])

In [46]:
# added noise to the database

augmented_database = db.float() * first_coin_flip+ (1- first_coin_flip) * second_coin_flip

In [47]:
torch.mean(augmented_database.float()) 

tensor(0.7100)

In [48]:
db_result = torch.mean(augmented_database.float()) * 2 - 0.5

In [49]:
def query(db): 
    
    true_result = torch.mean(db.float())
    
    first_coin_flip = (torch.rand(len(db)) > 0.5).float()
    second_coin_flip = (torch.rand(len(db)) > 0.5).float()
    
    augmented_database = db.float() * first_coin_flip + (1-first_coin_flip) * second_coin_flip
    
    db_result = torch.mean(augmented_database.float()) * 2 - 0.5
    
    return db_result, true_result

In [50]:
db, pdbs = create_db_and_parallels(100)
private_result, true_result = query(db)
print(" With Noise :"+ str(private_result))
print(" Without Noise :"+ str(true_result))


 With Noise :tensor(0.5400)
 Without Noise :tensor(0.4700)


In [51]:
db, pdbs = create_db_and_parallels(1000)
private_result, true_result = query(db)
print(" With Noise :"+ str(private_result))
print(" Without Noise :"+ str(true_result))


 With Noise :tensor(0.4960)
 Without Noise :tensor(0.4870)


In [52]:
db, pdbs = create_db_and_parallels(10000)
private_result, true_result = query(db)
print(" With Noise :"+ str(private_result))
print(" Without Noise :"+ str(true_result))

#slight difference between both datasets


 With Noise :tensor(0.5016)
 Without Noise :tensor(0.5010)


In [53]:
# Varying the amount of noise 

In [54]:
def query(db, noise = 0.2): 
    noise = 0.2
    true_result = torch.mean(db.float())

    first_coin_flip = (torch.rand(len(db)) > noise).float()
    second_coin_flip = (torch.rand(len(db)) > 0.5).float()

    augmented_database = db.float() * first_coin_flip + (1-first_coin_flip) * second_coin_flip

    db_result = torch.mean(augmented_database.float()) * 2 - 0.5
    
    sk_result = augmented_database.float().mean()
        
    private_result = ((sk_result / noise) - 0.5) * noise / (1-noise)

    return db_result, true_result

In [55]:
db, pdbs = create_db_and_parallels(100)
private_result, true_result = query(db, noise = 0.1)
print("With Noise :" + str(private_result))
print("Without Noise :" + str(true_result))

With Noise :tensor(0.5800)
Without Noise :tensor(0.5800)


In [56]:
db, pdbs = create_db_and_parallels(100)
private_result, true_result = query(db, noise = 0.2)
print("With Noise :" + str(private_result))
print("Without Noise :" + str(true_result))

With Noise :tensor(0.5800)
Without Noise :tensor(0.5500)


In [57]:
db, pdbs = create_db_and_parallels(100)
private_result, true_result = query(db, noise = 0.4)
print("With Noise :" + str(private_result))
print("Without Noise :" + str(true_result))

With Noise :tensor(0.4600)
Without Noise :tensor(0.4700)


In [58]:
# Large dataset

db, pdbs = create_db_and_parallels(10000)
private_result, true_result = query(db, noise = 0.8)
print("With Noise :" + str(private_result))
print("Without Noise :" + str(true_result))

With Noise :tensor(0.4880)
Without Noise :tensor(0.4960)


# GLOBAL Differential Privacy

In [59]:
# Add noise for Global Differential Privacy

# LAPLACIAN NOISE : delta is zero
# GAUSSIAN NOISE : delta value is presentabs

In [60]:
# Scenario : A Health neural network 

import numpy as np

In [61]:
num_teachers = 10 # 10 partner hospitals
num_examples = 10000 # size of dataset
num_labels = 10 # num of labels for our classifier


In [62]:
preds = (np.random.rand(num_teachers, num_examples)*num_labels).astype(int).transpose(1,0) # fake predictions

In [63]:
an_image = preds[:,0]

In [64]:
preds[:,0]

array([6, 0, 2, ..., 8, 7, 0])

In [65]:
np.bincount(an_image, minlength=num_labels) # Counts number of times an element occurs

# 9, 8 occurs 3 times

array([1001, 1024,  969, 1035, 1040,  965,  960,  980, 1018, 1008])

In [66]:
label_counts = np.bincount(an_image, minlength=num_labels)

In [67]:
np.argmax(label_counts) # finds the max ( here 8 is the first no. to occur max times)

4

In [68]:
epsilon = 0.1 
beta = 1/ epsilon

for i in range(len(label_counts)):
    label_counts[i] += np.random.laplace(0, beta, 1) # adding laplacian noise to the counts

In [69]:
label_counts

array([ 982, 1023,  954, 1024, 1037,  973,  967,  971, 1025, 1022])

In [70]:
np.argmax(label_counts)

4

In [71]:
new_labels = list()
for an_image in preds:
    
    label_counts = np.bincount(an_image, minlength=num_labels)
    
    epsilon = 0.1
    beta = 1/epsilon
    
    for i in range(len(label_counts)):
        label_counts[i] += np.random.laplace(0, beta, 1)
        
    new_label = np.argmax(label_counts)
    
    new_labels.append(new_label)

In [72]:
len(new_labels)

10000

In [73]:
new_labels

[8,
 4,
 4,
 6,
 0,
 4,
 2,
 0,
 8,
 1,
 1,
 9,
 7,
 9,
 7,
 8,
 0,
 8,
 1,
 8,
 2,
 8,
 7,
 3,
 0,
 6,
 9,
 3,
 1,
 5,
 7,
 4,
 9,
 0,
 9,
 1,
 3,
 5,
 5,
 3,
 7,
 6,
 3,
 9,
 7,
 2,
 8,
 1,
 3,
 9,
 8,
 2,
 6,
 1,
 2,
 7,
 7,
 8,
 7,
 9,
 0,
 5,
 4,
 8,
 1,
 2,
 5,
 7,
 1,
 7,
 6,
 2,
 6,
 3,
 2,
 4,
 5,
 0,
 1,
 2,
 6,
 4,
 5,
 9,
 1,
 0,
 8,
 0,
 6,
 4,
 7,
 8,
 8,
 9,
 6,
 9,
 0,
 6,
 2,
 2,
 3,
 8,
 6,
 5,
 3,
 6,
 8,
 5,
 5,
 0,
 2,
 1,
 8,
 3,
 5,
 1,
 8,
 7,
 8,
 8,
 1,
 0,
 5,
 2,
 1,
 5,
 5,
 8,
 2,
 2,
 3,
 5,
 6,
 2,
 5,
 5,
 6,
 8,
 8,
 1,
 9,
 6,
 2,
 8,
 0,
 2,
 4,
 6,
 1,
 2,
 7,
 4,
 4,
 9,
 2,
 9,
 5,
 4,
 4,
 6,
 9,
 0,
 1,
 0,
 7,
 3,
 0,
 2,
 5,
 2,
 8,
 8,
 8,
 2,
 3,
 0,
 2,
 8,
 8,
 0,
 6,
 6,
 2,
 4,
 2,
 8,
 8,
 4,
 5,
 4,
 9,
 6,
 3,
 8,
 5,
 9,
 6,
 7,
 8,
 3,
 4,
 0,
 2,
 2,
 9,
 9,
 8,
 7,
 9,
 1,
 7,
 5,
 1,
 5,
 5,
 0,
 4,
 3,
 3,
 9,
 2,
 1,
 1,
 5,
 8,
 8,
 8,
 9,
 7,
 1,
 0,
 2,
 0,
 8,
 1,
 9,
 1,
 5,
 2,
 8,
 8,
 0,
 2,
 1,
 0,
 6,
 9,
 7,
 4,
 7,


# PATE Analysis

In [74]:
labels = np.array([9, 9, 3, 6, 9, 9 ,9 ,9 ,8, 2])
counts = np.bincount(labels, minlength=10)
query_result = np.argmax(counts)
query_result

9

In [75]:
# PATE Analysis : 
# Remove one partition i.e. hospital and the query remains the same

In [76]:
#! pip install syft
#! pip install requests

In [77]:
from syft.frameworks.torch.dp import pate 

# dp : Differential Privacy


In [78]:
num_teachers, num_examples, num_labels = (100,100,10)
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int) # Fake Predictions
indices = (np.random.rand(num_examples) * num_labels).astype(int) # True answers


In [79]:
data_dep_eps, data_inde_eps = pate.perform_analysis(
                                            teacher_preds=preds, 
                                            indices=indices, 
                                            noise_eps=0.1, 
                                            delta= 1e-5)

print(" Data Independent Epsilon : ", data_inde_eps)
print(" Data Dependent Epsilon :   ", data_dep_eps)

 Data Independent Epsilon :  11.756462732485115
 Data Dependent Epsilon :    11.756462732485105


In [80]:
preds[:,0:5] *= 0

In [81]:
data_dep_eps, data_inde_eps = pate.perform_analysis(
                                            teacher_preds=preds, 
                                            indices=indices, 
                                            noise_eps=0.1, 
                                            delta= 1e-5)

print(" Data Independent Epsilon : ", data_inde_eps)
print(" Data Dependent Epsilon :   ", data_dep_eps)

 Data Independent Epsilon :  11.756462732485115
 Data Dependent Epsilon :    7.612485787172066


In [82]:
# More the values agree with each other , Tighter the Epsilon value

preds[:,0:50] *= 0

data_dep_eps, data_inde_eps = pate.perform_analysis(
                                            teacher_preds=preds, 
                                            indices=indices, 
                                            noise_eps=0.1, 
                                            delta= 1e-5)

print(" Data Independent Epsilon : ", data_inde_eps)
print(" Data Dependent Epsilon :   ", data_dep_eps)

 Data Independent Epsilon :  11.756462732485115
 Data Dependent Epsilon :    1.52655213289881


# Federated Learning

In [83]:
import torch as th

In [84]:
x = th.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [85]:
y = x+x

In [86]:
print(y)

tensor([ 2,  4,  6,  8, 10])


In [87]:
import syft as sy

In [88]:
hook = sy.TorchHook(th)

In [89]:
th.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [90]:
bob = sy.VirtualWorker(hook, id="bob")

In [91]:
bob._objects

{21868166705: <Plan Plan id:21868166705 owner:bob Tags: #fss_eq_plan_1 built>,
 77778314398: <Plan Plan id:77778314398 owner:bob Tags: #fss_eq_plan_2 built>,
 67081172097: <Plan Plan id:67081172097 owner:bob Tags: #fss_comp_plan_1 built>,
 2952485648: <Plan Plan id:2952485648 owner:bob Tags: #fss_comp_plan_2 built>,
 34072316813: <Plan Plan id:34072316813 owner:bob Tags: #xor_add_1 built>,
 27915031091: <Plan Plan id:27915031091 owner:bob Tags: #xor_add_2 built>}

In [92]:
x = th.tensor([1,2,3,4,5])

In [93]:
x = x.send(bob)

In [94]:
bob._objects

{21868166705: <Plan Plan id:21868166705 owner:bob Tags: #fss_eq_plan_1 built>,
 77778314398: <Plan Plan id:77778314398 owner:bob Tags: #fss_eq_plan_2 built>,
 67081172097: <Plan Plan id:67081172097 owner:bob Tags: #fss_comp_plan_1 built>,
 2952485648: <Plan Plan id:2952485648 owner:bob Tags: #fss_comp_plan_2 built>,
 34072316813: <Plan Plan id:34072316813 owner:bob Tags: #xor_add_1 built>,
 27915031091: <Plan Plan id:27915031091 owner:bob Tags: #xor_add_2 built>,
 37219026889: tensor([1, 2, 3, 4, 5])}

In [97]:
x.location == bob

True

In [98]:
x.id_at_location

37219026889

In [100]:
x.id

97159730238

In [102]:
x.owner

<VirtualWorker id:me #objects:0>

In [103]:
hook.local_worker

<VirtualWorker id:me #objects:0>

In [104]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [106]:
bob._objects

{21868166705: <Plan Plan id:21868166705 owner:bob Tags: #fss_eq_plan_1 built>,
 77778314398: <Plan Plan id:77778314398 owner:bob Tags: #fss_eq_plan_2 built>,
 67081172097: <Plan Plan id:67081172097 owner:bob Tags: #fss_comp_plan_1 built>,
 2952485648: <Plan Plan id:2952485648 owner:bob Tags: #fss_comp_plan_2 built>,
 34072316813: <Plan Plan id:34072316813 owner:bob Tags: #xor_add_1 built>,
 27915031091: <Plan Plan id:27915031091 owner:bob Tags: #xor_add_2 built>}

In [107]:
# Playing with remote tensors 

In [119]:
alice = sy.VirtualWorker(hook, id="alice")

In [120]:
x = th.tensor([1,2,3,4,5])

In [121]:
x_ptr = x.send(bob, alice)

In [122]:
x_ptr

(Wrapper)>[MultiPointerTensor]
	-> [PointerTensor | me:28232631285 -> bob:62863944882]
	-> [PointerTensor | me:8851392406 -> alice:62863944882]

In [123]:
x_ptr.child.child

{'bob': [PointerTensor | me:28232631285 -> bob:62863944882],
 'alice': [PointerTensor | me:8851392406 -> alice:62863944882]}

In [124]:
x_ptr.get()

[tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5])]

In [128]:
x = th.tensor([1,2,3,4,5]).send(bob,alice)

In [129]:
x.get(sum_results=True)

tensor([ 2,  4,  6,  8, 10])

In [130]:
# Remote Arithmetic